name: build
on:
  push:
  pull_request:
jobs:
  build_dist:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: dist
